version: '3'

services:

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - SQL_DATABASE=${SQL_DATABASE}
        - SQL_USER=${SQL_USER}
        - SQL_PASSWORD=${SQL_PASSWORD}
        - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
        - SQL_HOST=${SQL_HOST}
    volumes:
      - mariadb:/var/lib/mysql/
    environment:
        - SQL_DATABASE=${SQL_DATABASE}
        - SQL_USER=${SQL_USER}
        - SQL_PASSWORD=${SQL_PASSWORD}
        - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - inception

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        - WP_TITLE=${WP_TITLE}
        - WP_URL=${WP_URL}
        - WP_ADMIN_USER=${WP_ADMIN_USER}
        - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
    volumes:
      - wordpress:/var/www/
    depends_on:
      - mariadb
    restart: unless-stopped
    environment:
      - SQL_HOST=${SQL_HOST}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - WP_TITLE=${WP_TITLE}
      - WP_URL=${WP_URL}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
    expose:
      - "9000"

  nginx:
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress:/var/www/
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: unless-stopped

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/aurelien/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/aurelien/data/wordpress

networks:
  inception:
    name: inception
    driver: bridge
