version: '1'

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/abollen/data/mariadb
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/abollen/data/wordpress

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - SQL_DATABASE=${SQL_DATABASE}
        - SQL_USER=${SQL_USER}
        - SQL_PASSWORD=${SQL_PASSWORD}
        - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
        - SQL_HOST=${SQL_HOST}
    volumes:
      - mariadb:/var/lib/mysql/
    environment:
        - SQL_DATABASE=${SQL_DATABASE}
        - SQL_USER=${SQL_USER}
        - SQL_PASSWORD=${SQL_PASSWORD}
        - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
      - SQL_HOST=${SQL_HOST}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - WP_TITLE=${WP_TITLE}
      - WP_URL=${WP_URL}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_PATH=${WP_PATH}
    volumes:
      - wordpress:/var/www/
    depends_on:
      - mariadb
    environment:
      - SQL_HOST=${SQL_HOST}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - WP_TITLE=${WP_TITLE}
      - WP_URL=${WP_URL}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_PATH=${WP_PATH}

    restart: unless-stopped

  nginx:
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress:/var/www/
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: unless-stopped

